### ISSUE TITLE
pre-trained model file?

### ISSUE THREAD

**Issue by mnuriyumusak** [JeanN00B/Tomato-maturity-recognition---Mask-R-CNN-YOLOv8#1]
can you also share the yolov8 pre-trained model file so we can test in our computers?

**Comment by JeanN00B** [comment]
> can you also share the yolov8 pre-trained model file so we can test in our computers?

Yeah sure!... let me update the repo so you can find the YOLOv8 model trained as well

**Comment by mnuriyumusak** [comment]
thanks a lot.
